version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/$READTHEDOCS_LANGUAGE/conf.py
  fail_on_warning: false

# sphinx:
#   configuration: docs/zh_CN/conf.py
#   fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt