version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    sphinx:
      configuration: $LANGUAGE/conf.py
      fail_on_warning: false


python:
  install:
    - requirements: docs/requirements.txt